from typing import Any
from PyQt5 import QtCore, QtGui, QtWidgets
from new_wireframe_window import NewWireframeWindow

class MainWindow(object):
    def setupUi(self, MainWindow:Any) -> None:
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.partnerDialog = NewWireframeWindow()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label.setObjectName("label")
        self.display_file_list = QtWidgets.QListWidget(self.centralwidget)
        self.display_file_list.setGeometry(QtCore.QRect(10, 30, 131, 191))
        self.display_file_list.setObjectName("display_file_list")
        self.new_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_btn.setGeometry(QtCore.QRect(150, 30, 71, 31))
        self.new_btn.setObjectName("new_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(150, 70, 71, 31))
        self.delete_btn.setObjectName("delete_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(150, 110, 71, 31))
        self.clear_btn.setObjectName("clear_btn")
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(150, 150, 71, 31))
        self.refresh_btn.setObjectName("refresh_btn")
        self.transform_btn = QtWidgets.QPushButton(self.centralwidget)
        self.transform_btn.setGeometry(QtCore.QRect(150, 190, 71, 31))
        self.transform_btn.setObjectName("transform_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(10, 230, 61, 31))
        self.save_btn.setObjectName("save_btn")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setGeometry(QtCore.QRect(80, 230, 61, 31))
        self.load_btn.setObjectName("load_btn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 270, 211, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 280, 71, 21))
        self.label_2.setObjectName("label_2")
        self.nav_up_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nav_up_btn.setGeometry(QtCore.QRect(90, 330, 31, 26))
        self.nav_up_btn.setObjectName("nav_up_btn")
        self.nav_right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nav_right_btn.setGeometry(QtCore.QRect(120, 350, 31, 26))
        self.nav_right_btn.setObjectName("nav_right_btn")
        self.nav_down_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nav_down_btn.setGeometry(QtCore.QRect(90, 370, 31, 26))
        self.nav_down_btn.setObjectName("nav_down_btn")
        self.nav_left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nav_left_btn.setGeometry(QtCore.QRect(60, 350, 31, 26))
        self.nav_left_btn.setObjectName("nav_left_btn")
        self.nav_zoom_in_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.nav_zoom_in_btn_2.setGeometry(QtCore.QRect(130, 310, 31, 26))
        self.nav_zoom_in_btn_2.setObjectName("nav_zoom_in_btn_2")
        self.nav_zoom_out_btn = QtWidgets.QPushButton(self.centralwidget)
        self.nav_zoom_out_btn.setGeometry(QtCore.QRect(50, 310, 31, 26))
        self.nav_zoom_out_btn.setObjectName("nav_zoom_out_btn")
        self.viewport_frame = QtWidgets.QFrame(self.centralwidget)
        self.viewport_frame.setGeometry(QtCore.QRect(250, 30, 541, 391))
        self.viewport_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewport_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewport_frame.setObjectName("viewport_frame")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(220, 30, 20, 541))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 71, 21))
        self.label_3.setObjectName("label_3")
        self.log_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_browser.setGeometry(QtCore.QRect(250, 430, 541, 141))
        self.log_browser.setObjectName("log_browser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button_actions()



    def retranslateUi(self, MainWindow:Any) -> None:
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INE5420 SGI"))
        self.label.setText(_translate("MainWindow", "Display File"))
        self.new_btn.setText(_translate("MainWindow", "New"))
        self.delete_btn.setText(_translate("MainWindow", "Delete"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.transform_btn.setText(_translate("MainWindow", "Transform"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        self.label_2.setText(_translate("MainWindow", "Navigation"))
        self.nav_up_btn.setText(_translate("MainWindow", "▲"))
        self.nav_right_btn.setText(_translate("MainWindow", "▶"))
        self.nav_down_btn.setText(_translate("MainWindow", "▼"))
        self.nav_left_btn.setText(_translate("MainWindow", "◀"))
        self.nav_zoom_in_btn_2.setText(_translate("MainWindow", "➕"))
        self.nav_zoom_out_btn.setText(_translate("MainWindow", "➖"))
        self.label_3.setText(_translate("MainWindow", "Viewport"))


    def new_wireframe_window(self) -> None:
        self.partnerDialog.open_new()


    def button_actions(self) -> None:
        self.new_btn.clicked.connect(self.new_wireframe_window)
